bce_config:
    host: http://bcc.bj.baidubce.com
    bos_host: bj.bcebos.com
    spec: bcc.e1.c2m2
    root_disk_size_in_gb: 20
    security_group_id: ""
    zone_name: cn-bj-d
    ak: ""
    sk: ""
    # 服务器登陆密码，自己设置
    admin_pass: ""

appbuilder_config:
    # 运行路径
    workspace: /home/work/appbuilder

    # 运行命令，根据实际情况修改
    run_cmd: "python3 component_sample.py"
    # 本地用来打包的代码路径，根据实际情况修改
    local_dir: "./sample"

env:
    APPBUILDER_LOGLEVEL: debug
    APPBUILDER_TOKEN: ""