name: Go package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APPBUILDER_TOKEN: bce-v3/ALTAK-RPJR9XSOVFl6mb5GxHbfU/072be74731e368d8bbb628a8941ec50aaeba01cd
      APPBUILDER_TOKEN_V2: bce-v3/ALTAK-zX2OwTWGE9JxXSKxcBYQp/7dd073d9129c01c617ef76d8b7220a74835eb2f4
      APPBUILDER_TOKEN_V3: bce-v3/ALTAK-DKaql4wY9ojwp2uMe8IEj/7ae1190aff0684153de365381d9b06beab3064c5
      BAIDU_VDB_API_KEY: apaasTest1
      INSTANCE_ID: vdb-bj-vuzmppgqrnhv
      DATASET_ID: 2626a842-132f-45ce-977f-f701d18fd104
      APPBUILDER_TOKEN_DOC_FORMAT: bce-v3/ALTAK-bcKsgHd39g0Aaq3nCYUUQ/b06384229df1462c6fb011383d09230346a20ac4
      APP_ID: aa8af334-df27-4855-b3d1-0d249c61fc08
      DATASET_ID_V3: 4b2357ff-b7d5-4573-9187-ee29af2f8373
      DOCUMENT_ID: 120619f2-1b85-4e09-a36d-fc682168d09c
    strategy:
      fail-fast: false
      # 如果作业失败，是否立即停止其他作业的运行。设置为 false 意味着即使一个任务失败了，其他任务也会继续运行
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21.0', '1.22.0', '1.23.0']
      max-parallel: 2
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # 拉取代码

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        # 使用矩阵中的 Go 版本

    - name: Install dependencies
      run: |
        cd go/appbuilder
        go mod tidy
        # 切换到 go/appbuilder 目录并安装项目依赖

    - name: Run tests
      run: |
        cd go/appbuilder
        go test ./... -cover
        # 运行所有测试文件，并显示覆盖率