name: Go package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      # 如果作业失败，是否立即停止其他作业的运行。设置为 false 意味着即使一个任务失败了，其他任务也会继续运行
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21.0', '1.22.0', '1.23.0']
      max-parallel: 2
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # 拉取代码

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        # 指定需要的 Go 版本

    - name: Install dependencies
      run: |
        go mod tidy
        # 安装项目依赖

    - name: Run tests
      run: |
        go test ./go/appbuilder/agent_builder_test.go -cover
        go test ./go/appbuilder/app_builder_client_test.go -cover
        go test ./go/appbuilder/dataset_test.go -cover
        go test ./go/appbuilder/knowledge_base_test.go -cover
        go test ./go/appbuilder/rag_test.go -cover
        # 运行指定的单元测试文件,并显示覆盖率